set -g pane-border-style "fg={color0}"
set -g pane-active-border-style "fg={color4}"
set -g message-style "fg={foreground} bg={color0}"
set -g message-command-style "fg={color4} bg={color0}"
set -g mode-style "fg={background} bg={color4}"
set -g status-style "fg={color8} bg={background}"
set -g status-left "#[fg={color4},bold]  S #[fg={color8}]│ #[fg={color7}]#S "
set -g status-right "#[fg={color8}]#{{pane_current_path}} #[fg={color8}]│ #[fg={foreground}]%H:%M #[fg={color8}]│ #[fg={color8},dim]STR"
set -g window-status-format "#[fg={color8}] #I #[fg={color0}]#W "
set -g window-status-current-format "#[fg={background},bg={color4},bold] #I #[fg={foreground}]#W #[default]"
set -g window-status-bell-style "fg={color1},bold"
