[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding="0"

Font="JetBrainsMono Nerd Font"
FontSize="13"

KeyboardSize="0.4"

RoundCorners="8"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, MMMM d"

HeaderText="STR TERMINAL v3.0"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/str.jpg"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.4"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#4f5258"
DateTextColor="#4f5258"
TimeTextColor="#d6d8dc"

FormBackgroundColor="#0e0f11"
BackgroundColor="#0e0f11"
DimBackgroundColor="#0e0f11"

LoginFieldBackgroundColor="#1c1e21"
PasswordFieldBackgroundColor="#1c1e21"
LoginFieldTextColor="#d6d8dc"
PasswordFieldTextColor="#d6d8dc"
UserIconColor="#2980d4"
PasswordIconColor="#2980d4"

PlaceholderTextColor="#4f5258"
WarningColor="#c0392b"

LoginButtonTextColor="#0e0f11"
LoginButtonBackgroundColor="#2980d4"
SystemButtonsIconsColor="#4f5258"
SessionButtonTextColor="#4f5258"
VirtualKeyboardButtonTextColor="#4f5258"

DropdownTextColor="#d6d8dc"
DropdownSelectedBackgroundColor="#2980d4"
DropdownBackgroundColor="#1c1e21"

HighlightTextColor="#d6d8dc"
HighlightBackgroundColor="#2980d4"
HighlightBorderColor="#2980d4"

HoverUserIconColor="#3a9aef"
HoverPasswordIconColor="#3a9aef"
HoverSystemButtonsIconsColor="#2980d4"
HoverSessionButtonTextColor="#2980d4"
HoverVirtualKeyboardButtonTextColor="#2980d4"

#################### Form ####################

PartialBlur="true"
FullBlur="false"
BlurMax="16"
Blur="1.0"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="true"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername="yousef"
TranslatePlaceholderPassword="enter password"
TranslateLogin="LOGIN"
TranslateLoginFailedWarning="[ AUTH FAILED ]"
TranslateCapslockWarning="CAPS LOCK"
TranslateSuspend="SLEEP"
TranslateHibernate="HIBERNATE"
TranslateReboot="REBOOT"
TranslateShutdown="SHUTDOWN"
TranslateSessionSelection="SESSION"
TranslateVirtualKeyboardButtonOn="KB ON"
TranslateVirtualKeyboardButtonOff="KB OFF"
